apps/books/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^show/(?P<id>\d+)/$', views.show, name="show"),
    url(r'^edit/(?P<id>\d+)/$', views.edit, name="edit"),
    url(r'^new/$', views.new, name="new"),
    url(r'^new_review/$', views.new_review, name="new_review"),
    url(r'^process_new_book/$', views.process_new_book, name="process_new_book"),
    url(r'^delete/(?P<id>\d+)$', views.delete_review, name="delete_review")
]

apps/login_register/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^show/(?P<id>\d+)$', views.show, name="show"),
    url(r'^process_registration$', views.process_registration, name="process_registration"),
    url(r'^process_login$', views.process_login, name="process_login"),
    url(r'^logout/$', views.logout, name="logout")
]

belt2/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login_register.urls', namespace="login_register")),
    url(r'^books/', include('apps.books.urls', namespace="books"))
]

apps/books/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_register .models import User
from django.contrib import messages

# Create your models here.
class AuthorManager(models.Manager):
    def validate_author(self, request):
        existing = request.POST['existing_author']
        new_author = request.POST['new_author']
        errors = {
            'errors': []
        }
        if existing == "None" and new_author:
            #Create new author
            author_obj = Author.objects.create(
                name=request.POST['new_author']
            )
            #returns author object
            return author_obj
        elif not new_author and existing != "None":
            #Get id of existing author and return
            author_obj = Author.objects.get(id=request.POST['existing_author'])
            return author_obj
        elif new_author and existing != "None":
            msg = "Please only select a new or existing author"
            errors['errors'].append(msg)
        elif not new_author and existing == "None":
            msg = "Please enter a new or existing author"
            errors['errors'].append(msg)
        else:
            msg = "Something weird happened"
            errors['errors'].append(msg)
        if errors['errors']:
            for msg in errors['errors']:
                messages.error(request, msg)
            return False
        else:
            return True


    def create_author(self, request):
        print "*"*50
        print "IN THE CREATE AUTHOR FUNCTION"

class Author(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = AuthorManager()

class ReviewManager(models.Manager):
    def validate_review(self, request, book_obj=None):
        content = request.POST['review_content']
        rating = request.POST['rating']
        errors = {
            'errors': []
        }
        if len(content) < 3:
            msg = "Review content must contain at least 3 characters"
            errors['errors'].append(msg)
        if not rating:
            msg = "Please enter a rating"
            errors['errors'].append(msg)
        elif int(rating) < 1 or int(rating) > 5:
            msg = "Please enter a rating from 1 to 5"
            errors['errors'].append(msg)
        if errors['errors']:
            for msg in errors['errors']:
                messages.error(request, msg)
            return False
        else:
            print "IN THE ELSE FOR REVIEW"
            user_obj = User.objects.get(id=request.session['user'])
            review_obj = Review.objects.create(
                content = content,
                rating = rating,
                user = user_obj,
                book = book_obj
            )
            print review_obj
            return review_obj

class Review(models.Model):
    content = models.TextField()
    rating = models.IntegerField()
    user = models.ForeignKey(User)
    book = models.ForeignKey('Book')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ReviewManager()

class BookManager(models.Manager):
    def validate_book(self, request, author_obj=None):
        title = request.POST['title']
        errors = {
            'errors': []
        }
        if not title:
            msg = "Please provide a book title"
            errors['errors'].append(msg)
            print "*"*50
            print msg
        elif len(title) < 3:
            msg = "Title must be at least 3 characters"
            errors['errors'].append(msg)
            print "*"*50
            print msg
        if errors['errors']:
            for msg in errors['errors']:
                messages.error(request, msg)
            return False
        else:
            book_obj = Book.objects.create(
                title = title,
                author = author_obj
            )
            return book_obj

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()

apps/books/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

from .models import Author, Review, Book
from ..login_register .models import User

# Create your views here.
def index(request):
    user_obj = User.objects.get(id=request.session['user'])
    book_obj = Book.objects.all().order_by('-review__created_at')[:3]
    context = {
        'user': user_obj,
        'books': book_obj
    }
    return render(request, 'books/index.html', context)

def show(request, id):
    book = Book.objects.get(id=id)
    context = {'book': book}
    return render(request, 'books/show.html', context)

def edit(request, id):
    return render(request, 'books/edit.html')

def new(request):
    authors = Author.objects.all().distinct()
    context = {'authors': authors}
    return render(request, 'books/new.html', context)

def new_review(request):
    book_obj = Book.objects.get(id=request.POST['book_id'])
    review = Review.objects.validate_review(request, book_obj)
    return redirect(reverse('books:index'))

def process_new_book(request):
    if request.method == "POST":
        created_author = Author.objects.validate_author(request)
        if created_author:
            created_book = Book.objects.validate_book(request, created_author)
        else:
            return redirect(reverse('books:new'))
        if created_book:
            created_review = Review.objects.validate_review(request, created_book)
        else:
            return redirect(reverse('books:new'))
        if not created_review:
            return redirect(reverse('books:new'))
    else:
        return redirect(reverse('books:new'))
    return redirect(reverse('books:index'))

def delete_review(request, id):
    review = Review.objects.get(id=id)
    review.delete()
    return redirect(reverse('books:index'))

apps/books/templates/books/edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Page</title>
  </head>
  <body>
    <h1>Edit</h1>
  </body>
</html>

apps/books/templates/books/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index Page</title>
  </head>
  <body>
    <h5>Welcome, {{ user.first_name }}</h5>
    <a href="{% url 'login_register:logout' %}">Logout</a>
    <h2>Recent Book Reviews:</h2>
    <hr>
    {% for book in books %}
    <p><a href="{% url 'books:show' id=book.id %}">{{ book.title }}</a></p>
    <h6>Rating: {{ book.review_set.all.0.rating }}</h6>
    <p><a href="{% url 'login_register:show' id=book.review_set.all.0.user.id %}">{{ book.review_set.all.0.user.first_name }}</a> says: {{ book.review_set.all.0.content }}</p>
    <hr>
    {% endfor %}
    <h1>{{ books.0.review_set.all.0.user.first_name }}</h1>
  </body>
</html>

apps/books/templates/books/new.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New Page</title>
  </head>
  <body>
    {% if messages %}
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    {% endif %}
    <h1>Add a book and review</h1>
    <form action="{% url 'books:process_new_book' %}" method="POST">
      {% csrf_token %}
      <p>Book Title <input type="text" name="title"></p>
      <h5>Author:</h5>
      <p>Choose from the list:
        <select name="existing_author">
          <option value="None">None</option>
          {% for author in authors %}
          <option value="{{ author.id }}">{{ author.name }}</option>
          {% endfor %}
        </select>
      </p>
      <p>Or add a new author: <input type="text" name="new_author"></p>
      <p>Review: <textarea name="review_content"></textarea></p>
      <p>Rating: <input type="number" name="rating"></p>
      <input type="submit" value="Add Book and Review">
    </form>
  </body>
</html>

apps/books/templates/books/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Show Page</title>
  </head>
  <body>
    <h3>{{ book.title }}</h3>
    <p>Author: {{ book.author.name }}</p>
    <h5>Reviews</h5>
    <hr>
    {% for review in book.review_set.all %}
    <p>Rating: {{ review.rating }}</p>
    <p><a href="{% url 'login_register:show' id=review.user.id %}">{{ review.user.first_name }}</a>
      says: <em>{{ review.content }}</em></p>
    <p><em>Posted on {{ review.created_at }}</em></p>
    {% if request.session.user == review.user.id %}
    <form action="{% url 'books:delete_review' id=review.id %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="Delete Review">
    </form>
    {% endif %}
    <hr>
    {% endfor %}
    <form action="{% url 'books:new_review' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="book_id" value="{{ book.id }}">
      <p>Add a review: <textarea name="review_content"></textarea></p>
      <p>Rating: <input type="number" name="rating"></p>
      <input type="submit" value="Submit Review">
    </form>
  </body>
</html>